generated-initialize-release
initialize
	super initialize.
	identifierTokens := OrderedCollection new: 2.
	commaTokens := OrderedCollection new: 2.
	colonTokens := OrderedCollection new: 2.
	arrayTokens := OrderedCollection new: 2.
	leftBracketTokens := OrderedCollection new: 2.
	integerConstantTokens := OrderedCollection new: 2.
	periodPeriodTokens := OrderedCollection new: 2.
	rightBracketTokens := OrderedCollection new: 2.
	ofTokens := OrderedCollection new: 2.