generated-reduction actions
reduceActionForIndexedVariable1: nodes
	| result |
	result := Array new: 13.
	result at: 3 put: (OrderedCollection new: 2).
	result at: 4 put: (OrderedCollection new: 2).
	result at: 5 put: (OrderedCollection new: 2).
	result at: 6 put: (OrderedCollection new: 2).
	result at: 1 put: (nodes at: 1).
	result at: 2 put: (nodes at: 2).
	result at: 13 put: (nodes at: 4).
	^ result